[ workflows ] stack.yml: make ICU_VER part of the cache key (#6462)
Workflow `stack.yaml`:
- make `ICU_VER` part of the cache key
- use `--work-dir .stack-work-fast` for build without `text-icu`
- always write cache at the end of the action, replacing the old cache

diff --git a/src/github/workflows/stack.yml b/src/github/workflows/stack.yml
--- a/src/github/workflows/stack.yml
+++ b/src/github/workflows/stack.yml
@@ -19,6 +19,10 @@ on:
   pull_request:
     paths: *trigger_path_list
 
+# Github token needed to delete caches with gh
+env:
+  GH_TOKEN: ${{ github.token }}
+
 jobs:
   auto-cancel:
     if: |
@@ -75,6 +79,8 @@ jobs:
       # Use a known-good version of ICU from the msys2 repository since
       # GHC does not work with ICU ≠ 69
       ICU_URL: "https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-icu-69.1-1-any.pkg.tar.zst"
+      ICU_VER: "69.1"
+      # Andreas, 2023-01-21: the ICU_VER is needed for Windows, it is automatically determined on Linux/macOS.
 
     # Need bash on Windows for piping and evaluation.
     defaults:
@@ -82,6 +88,22 @@ jobs:
         shell: bash
 
     steps:
+
+    - name: Set up for the ICU library (macOS)
+      if: ${{ runner.os == 'macOS' }}
+      run: |
+        export ICU4C="$(brew --prefix)/opt/icu4c"
+        echo "PKG_CONFIG_PATH=${ICU4C}/lib/pkgconfig" >> "${GITHUB_ENV}"
+        echo "${ICU4C}/bin" >> "${GITHUB_PATH}"
+
+    - name: Determine the ICU version (Linux, macOS)
+      if: ${{ runner.os != 'Windows' }}
+      run: |
+        uconv --version
+        export ICU_VER="$(uconv --version | sed -ne 's/uconv v.* ICU \([0-9][0-9.]*\)/\1/p')"
+        echo "ICU_VER=${ICU_VER}"
+        echo "ICU_VER=${ICU_VER}" >> "${GITHUB_ENV}"
+      # The output of unconv --version looks like "uconv v2.1  ICU 72.1" from which we extract "72.1"
 
     # Checkout is needed before the first call to stack exec ${ARGS}
     # because it provides the stack-*.yaml file.
@@ -116,29 +138,6 @@ jobs:
         echo "ARGS=--stack-yaml=stack-${GHC_VER}.yaml --system-ghc --no-terminal"    >> ${GITHUB_ENV}
     # From now on, use env.GHC_VER rather than matrix.ghc-ver
 
-    # In a second step we can inspect and use the GITHUB_ENV set in the previous step:
-    - name: Environment (review)
-      run: |
-        echo "STACK_ROOT (fix)  = ${STACK_ROOT}"
-        echo "STACK_VER         = ${STACK_VER}"
-        echo "GHC_VER           = ${GHC_VER}"
-
-    - uses: actions/cache@v3
-      name: Cache dependencies
-      id: cache
-      with:
-        path: ${{ steps.haskell-setup.outputs.stack-root }}
-        # A unique cache is used for each stack.yaml.
-        # Note that matrix.stack-ver might be simply 'latest', so we use STACK_VER.
-        key: |
-          ${{ runner.os }}-stack-20230120-${{ env.STACK_VER }}-${{ env.GHC_VER }}-${{ hashFiles(format('stack-{0}.yaml', env.GHC_VER)) }}
-
-    - name: Set up pkg-config for the ICU library (macOS)
-      if: ${{ runner.os == 'macOS' }}
-      shell: bash
-      run: |
-        echo "PKG_CONFIG_PATH=$(brew --prefix)/opt/icu4c/lib/pkgconfig" >> ${GITHUB_ENV}
-
     # Note that msys2 libraries have to be installed via
     #   stack exec ${ARGS} -- pacman ...
     # because stack comes with its own msys2 instance, see
@@ -159,17 +158,49 @@ jobs:
         stack exec ${ARGS} -- bash -c "curl -LO ${ICU_URL} && pacman --noconfirm -U *.pkg.tar.zst"
         stack exec ${ARGS} -- pacman --noconfirm -S mingw-w64-x86_64-pkg-config
 
-    # - name: Install the numa library (Ubuntu, GHC 8.4.4)
-    #   if: ${{ runner.os == 'Linux' && env.GHC_VER == '8.4.4' }}
-    #   run: |
-    #     sudo apt-get install libnuma-dev -qq
+    - name: Environment (review)
+      run: |
+        echo "STACK_ROOT (fix)  = ${STACK_ROOT}"
+        echo "STACK_VER         = ${STACK_VER}"
+        echo "GHC_VER           = ${GHC_VER}"
+        echo "ICU_VER           = ${ICU_VER}"
+
+    - name: Restore cache
+      uses: actions/cache/restore@v3
+      id:   cache
+      with:
+        # A unique cache is used for each stack.yaml.
+        # Note that matrix.stack-ver might be simply 'latest', so we use STACK_VER.
+        key:  &cache_key ${{ runner.os }}-icu-${{ env.ICU_VER }}-stack-${{ env.STACK_VER }}-ghc-${{ env.GHC_VER }}-${{ hashFiles(format('stack-{0}.yaml', env.GHC_VER)) }}
+        path: &cache_pathes |
+          ${{ env.STACK_ROOT }}
+        # Andreas, 2023-01-23: also caching the two work dirs balloons a cache entry from 300MB to 800MB,
+        # which is more than we can tolerate with out total cache size of mac 10GB.
+          # .stack-work
+          # .stack-work-fast
 
     - name: Install dependencies for Agda and `agda-tests` (i.e. the test suite).
-      if: ${{ !steps.cache.outputs.cache-hit }}
+      # if: ${{ !steps.cache.outputs.cache-hit }}
       run: stack build ${ARGS} ${EXTRA_ARGS} ${NON_DEFAULT_FLAGS} --test --only-dependencies
 
     - name: Build Agda with the default flags in Agda.cabal. Also build `agda-tests` (i.e. the test suite).
-      run: stack build ${ARGS} ${EXTRA_ARGS} --test --no-run-tests
+      run: stack build ${ARGS} ${EXTRA_ARGS} --work-dir=.stack-work-fast --test --no-run-tests
 
     - name: Build Agda with the non-default flags Agda.cabal.
       run: stack build ${ARGS} ${EXTRA_ARGS} ${NON_DEFAULT_FLAGS}
+
+    - name: Clear cache
+      if:   ${{ steps.cache.outputs.cache-hit }}
+      env:
+        KEY: *cache_key
+      run: |
+        gh extension install actions/gh-actions-cache
+        gh actions-cache delete ${{ env.KEY }} --confirm || true
+      # Don't fail if cache cannot be deleted
+
+    - name: Save cache
+      uses: actions/cache/save@v3
+      if:   always()  # save cache even when build fails
+      with:
+        key:  *cache_key
+        path: *cache_pathes
